# Generated by Django 2.0.5 on 2020-06-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp_Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('idnentity', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('address', models.CharField(max_length=20)),
            ],
        ),
    ]
